name: JoinUtils
author: JasperEdits
version: 1.1.2
main: me.jasperedits.joinutils.core.Main
description: A very simple spawn-on-join plugin, with some extra features.

commands:
  spawn:
     aliases: []
  jureload:
     aliases: [joinutilsreload, joinutilitiesreload]