############################
# JoinUtils by JasperEdits #
############################

spawn:
   world: yourworld
   gamemode: survival
   x: 0
   y: 0
   z: 0
   yaw: 180
   pitch: 0

modules:
   motd: true
   spawnonjoin: true
   spawncmd: true
    
motd:
   - "&aMOTD example."
   - "&eYou can add multiple lines."
   
messages: # Set it to "0" or 0 to disable the message.
   spawncmd:  
      onlyplayers: "&cThis command can only be executed by a player."
      teleporting: "&aTeleporting to spawn."
      disabled: "&cThis command is disabled."
      