name: SimpleSpawn
author: JasperEdits
version: 1.0
main: me.jasperedits.simplespawn.core.Main
description: A very simple spawn-on-join plugin, with some extra features.

commands:
  spawn:
     aliases: []
  